spring:
  application:
    name: sync-money
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

logging:
  level:
    ROOT: OFF
    dev.thiagooliveira: INFO

app:
  jwt:
    secret: bXlTdXBlclNlY3JldEtleUluQmFzZTY0Rm9ybWF0