###

# Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "{{user.email}}",
  "name": "{{user.name}}",
  "password": "{{user.password}}"
}

###

# Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{user.email}}",
  "password": "{{user.password}}"
}

###

# Get Users
GET {{baseUrl}}/api/users
Authorization: Bearer {{accessToken}}

###

# Invite User
POST {{baseUrl}}/api/users/invites
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "email": "{{invitedUser.email}}"
}

###

# Get Invitations
GET {{baseUrl}}/api/users/invites
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

# Register Invited User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "{{invitedUser.email}}",
  "name": "{{invitedUser.name}}",
  "password": "{{invitedUser.password}}"
}

###

# Create Europe Bank
POST {{baseUrl}}/api/banks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Europe Bank",
  "currency": "EUR"
}

###

# Create Brazil Bank
POST {{baseUrl}}/api/banks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Brazil Bank",
  "currency": "BRL"
}

###

# Get Banks
GET {{baseUrl}}/api/banks
Authorization: Bearer {{accessToken}}

###

# Create Europe Account
POST {{baseUrl}}/api/accounts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Europe Account",
  "bankId": "3226011d-8072-47d9-abbf-9ac67ae68005",
  "initialBalance": 1000.0
}

###

# Create Brazil Account
POST {{baseUrl}}/api/accounts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Brazil Account",
  "bankId": "55642a18-5b81-4c0e-a56f-fcd4b708a38f",
  "initialBalance": 1000.0
}

###

# Get Accounts
GET {{baseUrl}}/api/accounts
Authorization: Bearer {{accessToken}}

###

# Get Account By Id
GET {{baseUrl}}/api/accounts/{{accountId1}}
Authorization: Bearer {{accessToken}}

###

# Get Categories
GET {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}

###

### Create Salary 1
POST {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Salary 1",
  "type": "CREDIT"
}

### Create Salary 2
POST {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Salary 2",
  "type": "CREDIT"
}

### Create Apartment Rental
POST {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Apartment Rental",
  "type": "DEBIT"
}

### Create Electricity Bill
POST {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Electricity Bill",
  "type": "DEBIT"
}

### Create Water Bill
POST {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Water Bill",
  "type": "DEBIT"
}

### Create Food
POST {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Food",
  "type": "DEBIT"
}

### Create Leisure
POST {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Leisure",
  "type": "DEBIT"
}

###

### Create Brazil Transfer
POST {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Brazil Transfer",
  "type": "DEBIT"
}

###

### Create Europe Transfer
POST {{baseUrl}}/api/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Europe Transfer",
  "type": "CREDIT"
}

###

# Get Transactions
POST {{baseUrl}}/api/transactions/2025-08-01
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "accountIds": [
    "{{accountId1}}",
    "{{accountId2}}"
  ]
}
###

# Create Deposit
POST {{baseUrl}}/api/accounts/{{accountId1}}/deposit
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "dateTime": "2025-07-29T20:24:00+01:00",
  "description": "Deposit test",
  "categoryId": "11111111-1111-1111-1111-111111111111",
  "amount": 10.0
}

###

# Create Withdraw
POST {{baseUrl}}/api/accounts/{{accountId1}}/withdraw
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "dateTime": "2025-07-29T20:24:00+01:00",
  "description": "Withdraw test",
  "categoryId": "22222222-2222-2222-2222-222222222222",
  "amount": 10.0
}

###

# Create Receivable
POST {{baseUrl}}/api/accounts/{{accountId1}}/receivables
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "startDate": "2025-07-30",
  "description": "Salary 1",
  "categoryId": "b93ba696-706c-4a81-afc2-529dc6d7c523",
  "amount": 1000.0,
  "recurring": true
}

###

# Create Payable
POST {{baseUrl}}/api/accounts/{{accountId1}}/payables
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "startDate": "2025-07-30",
  "description": "Apartment Rental",
  "categoryId": "2ec624ca-4658-4787-afe8-2a529b7e7225",
  "amount": 300.0,
  "recurring": true
}

###

# Pay Scheduled Transaction
POST {{baseUrl}}/api/accounts/{{accountId1}}/transactions/a290fb18-542d-4091-bc56-9c13f9e91e77/pay
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "dateTime": "2025-07-29T16:30:00+01:00",
  "amount": 1000.0
}

###

# Create Transfer
POST {{baseUrl}}/api/transfers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "sourceAccountId": "{{accountId1}}",
  "targetAccountId": "{{accountId2}}",
  "sourceAmount": 100,
  "targetAmount": 637.35,
  "sourceCategoryId": "12c93427-4a5c-450e-9cb6-1c5ba3db699b",
  "targetCategoryId": "c4a2472c-44db-41fe-8e28-566ac4f3c143"
}

###

# Get Account Summary
POST {{baseUrl}}/api/summary/2025-08-01
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "accountIds": [
    "{{accountId1}}",
    "{{accountId2}}"
  ]
}
###

