openapi: 3.0.3
info:
  title: Users API
  version: 1.0.0
  description: Users API

tags:
  - name: Users
    description: Endpoints related to users
  - name: Auth
    description: Endpoints related to authentication
paths:
  /api/auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRegisterRequestBody'
      responses:
        '201':
          description: Registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostRegisterResponseBody'
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostLoginRequestBody'
      responses:
        '200':
          description: Login successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostLoginResponseBody'
  /api/users:
    get:
      tags:
        - Users
      summary: Retrieve all users
      operationId: listUsers
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetUsersResponseBody'
  /api/users/me:
    get:
      tags:
        - Users
      summary: Retrieve the current user data
      operationId: getById
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponseBody'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    PostLoginRequestBody:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    PostLoginResponseBody:
      type: object
      properties:
        token:
          type: string
    PostRegisterRequestBody:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
    PostRegisterResponseBody:
      type: object
      properties:
        id:
          type: string
          format: uuid
    GetUsersResponseBody:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          scopes: {}

security:
  - ClientCredentials: []